- platform: rest
  name: Pollen
  scan_interval: 600
  resource: !secret tomorrow-api-pollen
  json_attributes_path: "$.data.timelines[0].intervals[0].values"
  json_attributes:
    - treeIndex
    - weedIndex
    - grassIndex
  value_template: >-
    {{ value_json.message }}

- platform: template
  sensors:
  
    pollen_tree:
      friendly_name: "Pollen - Trees"
      value_template: '{{ int(states.sensor.pollen.attributes["treeIndex"], default=0) }}'

    pollen_weed:
      friendly_name: "Pollen - Weeds"
      value_template: '{{ int(states.sensor.pollen.attributes["weedIndex"], default=0) }}'

    pollen_grass:
      friendly_name: "Pollen - Grasses"
      value_template: '{{ int(states.sensor.pollen.attributes["grassIndex"], default=0) }}'

